### ISSUE TITLE
Point-cloud tracker improvements

### ISSUE THREAD

**Issue by imagejan** [fmi-faim/fmi-trackmate-addons#7]
See `improved-tracking` branch.

* [x] Return pruned graph (no links skipping over spots)
* [ ] Add setting to select between raw graph (with edge weights corresponding to model cost) and pruned graph
* [ ] Implement minCoverage filtering as defined in settings
* [ ] Clean up config panel
